import type {
	ApplicationStatus,
	AttributionRule,
	AttributionStatus,
	CampaignStatus,
	PartnerStatus,
	PayoutStatus,
} from "./partner-enums";

/** A channel partner (PRD-046 §14 `Partner`). */
export interface Partner {
	readonly id: string;
	readonly orgName: string;
	readonly contactPerson: string;
	readonly email: string;
	readonly phone: string;
	readonly status: PartnerStatus;
	readonly createdAt: Date;
}

/** A partner onboarding application — the manual-decision hook record. */
export interface PartnerApplication {
	readonly id: string;
	readonly partnerId: string;
	readonly orgName: string;
	readonly contactPerson: string;
	readonly email: string;
	readonly phone: string;
	readonly status: ApplicationStatus;
	readonly decisionReason: string | null;
	readonly decidedBy: string | null;
	readonly decidedAt: Date | null;
	readonly createdAt: Date;
}

/** Optional usage caps on a campaign (e.g. max credited conversions). */
export interface CampaignCaps {
	readonly maxConversions?: number;
}

/** A referral/campaign link + coupon pair generated by an approved partner. */
export interface Campaign {
	readonly id: string;
	readonly partnerId: string;
	readonly name: string;
	/** Token captured at signup time (first-touch referral link). */
	readonly linkToken: string;
	/** Coupon code applied at checkout time. */
	readonly referralCode: string;
	readonly status: CampaignStatus;
	readonly caps: CampaignCaps | null;
	readonly createdAt: Date;
}

/** A single attribution — a signup touch, optionally credited by a paid conversion. */
export interface AttributionRecord {
	readonly id: string;
	readonly partnerId: string;
	readonly campaignId: string;
	readonly studentId: string;
	readonly registrationId: string | null;
	readonly status: AttributionStatus;
	readonly ruleApplied: AttributionRule | null;
	/** Paid-conversion amount in paise; set once credited. Commission is computed from this. */
	readonly amountPaise: number | null;
	readonly convertedAt: Date | null;
	readonly createdAt: Date;
}

/** Per-campaign funnel counts within a partner's overall funnel. */
export interface CampaignFunnel {
	readonly campaignId: string;
	readonly campaignName: string;
	readonly signups: number;
	readonly registrations: number;
	readonly paid: number;
}

/** Partner-level funnel read model (signups -> registrations -> paid). */
export interface PartnerFunnel {
	readonly partnerId: string;
	readonly signups: number;
	readonly registrations: number;
	readonly paid: number;
	readonly byCampaign: readonly CampaignFunnel[];
}

/**
 * A specific amount admin decided to send a partner, and whether it has
 * actually gone out yet. Not derived from any commission calculation — admin
 * sets `amountPaise` directly when triggering.
 */
export interface Payout {
	readonly id: string;
	readonly partnerId: string;
	readonly amountPaise: number;
	/** What this covers, freeform — e.g. "August referrals". */
	readonly note: string | null;
	readonly status: PayoutStatus;
	readonly triggeredBy: string;
	readonly triggeredAt: Date;
	readonly paidBy: string | null;
	readonly paidAt: Date | null;
}

/**
 * Where a partner's payouts get sent. Account number and PAN are the only
 * fields sensitive enough to encrypt (see `infra/bank-details-encryption.ts`)
 * — this shape carries only their masked companions; the plaintext is
 * reachable solely through `BankDetailsService.reveal`.
 */
export interface BankDetails {
	readonly partnerId: string;
	readonly accountHolderName: string;
	readonly bankName: string;
	readonly ifscCode: string;
	readonly accountNumberLast4: string;
	readonly panMasked: string;
	readonly submittedAt: Date;
	readonly updatedAt: Date;
}

/** A partner<->institution assignment (self-service, audited). */
export interface PartnerInstitutionAssignment {
	readonly id: string;
	readonly partnerId: string;
	readonly institutionId: string;
	readonly effectiveFrom: Date;
	readonly effectiveTo: Date | null;
	readonly assignedBy: string;
}
