import type {
	ApplicationStatus,
	AttributionRule,
	AttributionStatus,
	CampaignStatus,
	PartnerStatus,
	PayoutStatus,
	StatementStatus,
} from "./partner-enums";

/** A channel partner (PRD-046 §14 `Partner`). */
export interface Partner {
	readonly id: string;
	readonly orgName: string;
	readonly contactPerson: string;
	readonly email: string;
	readonly phone: string;
	/** Overrides the platform default commission rate for this partner. */
	readonly commissionRatePct: number;
	readonly status: PartnerStatus;
	readonly createdAt: Date;
}

/** A partner onboarding application — the manual-decision hook record. */
export interface PartnerApplication {
	readonly id: string;
	readonly partnerId: string;
	readonly orgName: string;
	readonly contactPerson: string;
	readonly email: string;
	readonly phone: string;
	readonly status: ApplicationStatus;
	readonly decisionReason: string | null;
	readonly decidedBy: string | null;
	readonly decidedAt: Date | null;
	readonly createdAt: Date;
}

/** Optional usage caps on a campaign (e.g. max credited conversions). */
export interface CampaignCaps {
	readonly maxConversions?: number;
}

/** A referral/campaign link + coupon pair generated by an approved partner. */
export interface Campaign {
	readonly id: string;
	readonly partnerId: string;
	readonly name: string;
	/** Token captured at signup time (first-touch referral link). */
	readonly linkToken: string;
	/** Coupon code applied at checkout time. */
	readonly referralCode: string;
	readonly status: CampaignStatus;
	readonly caps: CampaignCaps | null;
	readonly createdAt: Date;
}

/** A single attribution — a signup touch, optionally credited by a paid conversion. */
export interface AttributionRecord {
	readonly id: string;
	readonly partnerId: string;
	readonly campaignId: string;
	readonly studentId: string;
	readonly registrationId: string | null;
	readonly status: AttributionStatus;
	readonly ruleApplied: AttributionRule | null;
	/** Paid-conversion amount in paise; set once credited. Commission is computed from this. */
	readonly amountPaise: number | null;
	readonly convertedAt: Date | null;
	readonly createdAt: Date;
}

/** Per-campaign funnel counts within a partner's overall funnel. */
export interface CampaignFunnel {
	readonly campaignId: string;
	readonly campaignName: string;
	readonly signups: number;
	readonly registrations: number;
	readonly paid: number;
}

/** Partner-level funnel read model (signups -> registrations -> paid). */
export interface PartnerFunnel {
	readonly partnerId: string;
	readonly signups: number;
	readonly registrations: number;
	readonly paid: number;
	readonly byCampaign: readonly CampaignFunnel[];
}

/** A single commission line item, one per credited attribution. */
export interface CommissionLineItem {
	readonly attributionId: string;
	readonly campaignId: string;
	readonly studentId: string;
	readonly registrationId: string;
	readonly amountPaise: number;
	readonly commissionRatePct: number;
	readonly commissionPaise: number;
}

/** An immutable, versioned commission statement for a partner+period. */
export interface CommissionStatement {
	readonly id: string;
	readonly partnerId: string;
	/** Billing period, e.g. "2026-06". */
	readonly period: string;
	/** Monotonic version for this partner+period; version 1 never changes once issued. */
	readonly version: number;
	readonly lineItems: readonly CommissionLineItem[];
	readonly totalPaise: number;
	readonly status: StatementStatus;
	readonly issuedAt: Date;
}

/** A payout ledger entry created from an issued commission statement. */
export interface PayoutLedgerEntry {
	readonly id: string;
	readonly partnerId: string;
	readonly statementId: string;
	readonly amountPaise: number;
	readonly status: PayoutStatus;
	readonly financeSignOffApprover: string | null;
	readonly financeSignOffAt: Date | null;
	readonly reason: string | null;
	readonly createdAt: Date;
}

/** A partner<->institution assignment (self-service, audited). */
export interface PartnerInstitutionAssignment {
	readonly id: string;
	readonly partnerId: string;
	readonly institutionId: string;
	readonly effectiveFrom: Date;
	readonly effectiveTo: Date | null;
	readonly assignedBy: string;
}
