// Input (driving) port interfaces — add your use-case ports here.
export type {
	AdminAuthContext,
	RequireRole,
	RoleRequirement,
} from "./admin-auth.port.ts";
export type {
	AssignInstitutionInput,
	AttributionUseCase,
	BankDetailsUseCase,
	CampaignUseCase,
	CapturePaidConversionInput,
	CaptureSignupInput,
	CreateCampaignInput,
	DecidePartnerApplicationInput,
	DecidePartnerApplicationUseCase,
	ExportKind,
	ExportUseCase,
	GetPartnerApplicationUseCase,
	GetPartnerUseCase,
	InstitutionAssignmentUseCase,
	MarkPayoutPaidInput,
	PayoutUseCase,
	SubmitBankDetailsInput,
	SubmitPartnerApplicationInput,
	SubmitPartnerApplicationUseCase,
	TriggerPayoutInput,
	UnassignInstitutionInput,
	UpdateCampaignInput,
} from "./partner.port.ts";
