// Re-export all port interfaces for convenient imports.
export type {
	AdminAuthContext,
	AssignInstitutionInput,
	AttributionUseCase,
	BankDetailsUseCase,
	CampaignUseCase,
	CapturePaidConversionInput,
	CaptureSignupInput,
	CreateCampaignInput,
	DecidePartnerApplicationInput,
	DecidePartnerApplicationUseCase,
	ExportKind,
	ExportUseCase,
	GetPartnerApplicationUseCase,
	GetPartnerUseCase,
	InstitutionAssignmentUseCase,
	MarkPayoutPaidInput,
	PayoutUseCase,
	RequireRole,
	RoleRequirement,
	SubmitBankDetailsInput,
	SubmitPartnerApplicationInput,
	SubmitPartnerApplicationUseCase,
	TriggerPayoutInput,
	UnassignInstitutionInput,
	UpdateCampaignInput,
} from "./in/index.ts";
export type {
	AdminCapability,
	AdminRole,
	AiProviderPort,
	AiUsage,
	AttributionRepository,
	AuditActor,
	AuditActorType,
	AuditEvent,
	AuditOutcome,
	AuditResource,
	AuditSink,
	AuthKitClaims,
	AuthorizationDecision,
	AuthorizationPolicyPort,
	BankDetailsCrypto,
	BankDetailsRepository,
	CampaignRepository,
	Clock,
	GenerateStructuredOutputParams,
	GenerateStructuredOutputResult,
	GenerateTextParams,
	GenerateTextResult,
	IdGenerator,
	NewCampaign,
	NewPartnerApplication,
	PartnerApplicationRepository,
	PartnerAuthContext,
	PartnerAuthorizationDecision,
	PartnerAuthorizationPort,
	PartnerDomainEvent,
	PartnerEventPublisher,
	PartnerInstitutionAssignmentRepository,
	PartnerRepository,
	PayoutRepository,
} from "./out/index.ts";
export {
	ADMIN_CAPABILITIES,
	ADMIN_CAPABILITY_MAP,
	ADMIN_ROLES,
	denyByDefaultPartnerPolicy,
	isStaffRole,
} from "./out/index.ts";
