// Re-export all port interfaces for convenient imports.
export type {
	AdminAuthContext,
	AssignInstitutionInput,
	AttributionUseCase,
	CampaignUseCase,
	CapturePaidConversionInput,
	CaptureSignupInput,
	CommissionUseCase,
	CreateCampaignInput,
	DecidePartnerApplicationInput,
	DecidePartnerApplicationUseCase,
	ExportKind,
	ExportUseCase,
	GenerateStatementInput,
	GetPartnerApplicationUseCase,
	GetPartnerUseCase,
	InstitutionAssignmentUseCase,
	PayoutUseCase,
	RequireRole,
	RoleRequirement,
	SubmitPartnerApplicationInput,
	SubmitPartnerApplicationUseCase,
	UnassignInstitutionInput,
	UpdateCampaignInput,
	UpdatePayoutStatusInput,
} from "./in/index.ts";
export type {
	AdminCapability,
	AdminRole,
	AiProviderPort,
	AiUsage,
	AttributionRepository,
	AuditActor,
	AuditActorType,
	AuditEvent,
	AuditOutcome,
	AuditResource,
	AuditSink,
	AuthKitClaims,
	AuthorizationDecision,
	AuthorizationPolicyPort,
	CampaignRepository,
	Clock,
	CommissionStatementRepository,
	GenerateStructuredOutputParams,
	GenerateStructuredOutputResult,
	GenerateTextParams,
	GenerateTextResult,
	IdGenerator,
	NewCampaign,
	NewPartnerApplication,
	PartnerApplicationRepository,
	PartnerAuthContext,
	PartnerAuthorizationDecision,
	PartnerAuthorizationPort,
	PartnerDomainEvent,
	PartnerEventPublisher,
	PartnerInstitutionAssignmentRepository,
	PartnerRepository,
	PayoutLedgerRepository,
} from "./out/index.ts";
export {
	ADMIN_CAPABILITIES,
	ADMIN_CAPABILITY_MAP,
	ADMIN_ROLES,
	denyByDefaultPartnerPolicy,
	isStaffRole,
} from "./out/index.ts";
